    - name: Add Nodesource Keys
      become: yes
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add Nodesource Apt Sources
      become: yes
      apt_repository:
        repo: '{{ item }}'
        state: present
      with_items:
        - 'deb https://deb.nodesource.com/node_6.x xenial main'
        - 'deb-src https://deb.nodesource.com/node_6.x xenial main'

    - name: Install NodeJS and NPM
      become: yes
      apt:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      with_items:
        - nodejs
        - git
 

    #Clone git repo

    - name: Clone repo
      git:
        repo: "https://{{ githubuser | urlencode }}:{{ githubpwd | urlencode }}@github.ncsu.edu/vrpandey/Homework1Part2.git"
        clone: yes
        dest: /files/hw1Repo
        force: yes

